# Generated by Django 6.1.1 on 2026-09-27 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Entrou no sistema'), ('LOGIN_FALHA', 'Erro ao entrar'), ('ACESSO_APROVADO', 'Aprovou pedido de acesso'), ('ACESSO_RECUSADO', 'Recusou pedido de acesso'), ('RELATORIO_PUBLICADO', 'Publicou relatório')], max_length=30)),
                ('usuario_informado', models.CharField(blank=True, max_length=150)),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-quando'],
            },
        ),
    ]
