# Generated by Django 6.1.1 on 2026-09-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Entrou no sistema'), ('LOGIN_FALHA', 'Erro ao entrar'), ('ACESSO_APROVADO', 'Aprovou pedido de acesso'), ('ACESSO_RECUSADO', 'Recusou pedido de acesso'), ('RELATORIO_PUBLICADO', 'Publicou relatório'), ('EMAIL', 'Aviso por e-mail')], max_length=30),
        ),
    ]
