# Generated by Django 6.1.1 on 2026-09-09 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_letivo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('conteudo', models.TextField()),
                ('tarefa_descricao', models.TextField(blank=True)),
                ('tarefa_data_entrega', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relatorios.turma')),
            ],
            options={
                'ordering': ['-data_aula'],
            },
        ),
    ]
