# Generated by Django 6.1.1 on 2026-09-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ativo',
        ),
    ]
