# Generated by Django 6.1.1 on 2026-09-21 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relatorios', '0004_remove_perfil_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('aceite_termos_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_acesso', to='relatorios.aluno')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de acesso',
                'verbose_name_plural': 'solicitações de acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
