# Generated by Django 6.1.1 on 2026-10-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aceite dos termos',
                'verbose_name_plural': 'aceites dos termos',
                'ordering': ['-aceito_em'],
                'unique_together': {('usuario', 'versao')},
            },
        ),
    ]
